apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: guacamoleconnections.guacamole.ukserp.ac.uk
spec:
  group: guacamole.ukserp.ac.uk
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                hostname:
                  type: string
                  description: Url to the host.
                port:
                  type: integer
                  description: Port number for the host.
                protocol:
                  type: string
                  description: Protocol for the connection.

                ldap:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      description: Synchronize user access to the connection from LDAP group membership.
                      default: false
                    groupFilter:
                      type: string
                      description: LDAP search filter returning one or more groups under the LDAP group base set on the controller deployment.
  scope: Namespaced
  names:
    plural: guacamoleconnections
    singular: guacamoleconnection
    kind: GuacamoleConnection
