apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: guacamoleconnection.guacamole.ukserp.ac.uk
spec:
  group: guacamole.ukserp.ac.uk
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                url:
                  type: string
                  description: Url to poll over http(s).
  scope: Namespaced
  names:
    plural: guacamoleconnections
    singular: guacamoleconnection
    kind: GuacamoleConnection
