{{- if .Values.ldap.createSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guacamole.ldap.secret" . }}

  labels:
    app: {{ include "guacamole.labels.app" . }}
    component: ldap
    chart: {{ include "guacamole.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

type: kubernetes.io/basic-auth
data:
  username: {{ .Values.ldap.createSecret.username | b64enc }}
  password: {{ .Values.ldap.createSecret.password | b64enc }}
{{- end }}
