{{- if .Values.controller.createSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guacamole.controller.secret" . }}

  labels:
    app: {{ include "guacamole.labels.app" . }}
    component: controller
    chart: {{ include "guacamole.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

type: kubernetes.io/basic-auth
data:
  username: {{ .Values.controller.createSecret.username | b64enc }}
  password: {{ .Values.controller.createSecret.password | b64enc }}
{{- end }}
