apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "guacamole.fullname" . }}-controller
subjects:
- kind: ServiceAccount
  name: {{ include "guacamole.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "guacamole.fullname" . }}-controller
  apiGroup: rbac.authorization.k8s.io
