crds:
  enabled: false

defaultNodeSelector: {}
defaultAffinity: {}
defaultTolerations: []

defaultSecurityContext:
  fsGroup: 0

extraEnv: []
extraVolumeMounts: []
extraVolumes: []

extraManifests: []

################################################################################

ldap:

  hostname:
  port:
  userBaseDn:
  groupBaseDn:
  usernameAttribute:
  memberAttribute:
  searchFilter:

  secret:
  createSecret:
    create: false
    username: bind
    password: password

################################################################################
controller:
  enabled: false

  image:
    repository: harbor.ukserp.ac.uk/guacamole/controller
    tag: 1.0.0
    pullPolicy: IfNotPresent
    pullSecret: ""
    uid: 1001
    gid: 0

  secret:
  createSecret:
    create: false
    username: guaccontroller
    password: password

  replicas: 1

  resources: {}

  nodeSelector: {}
  affinity: {}
  tolerations: []

  securityContext: {}

  labels: {}
  podLabels: {}

  annotations: {}
  podAnnotations: {}

  extraEnv: []
  extraVolumeMounts: []
  extraVolumes: []

################################################################################
guacd:
  enabled: true

  image:
    repository: guacamole/guacd
    tag: 1.5.3
    pullPolicy: IfNotPresent
    pullSecret: ""
    uid: 1001
    gid: 0

  port: 4822

  replicas: 1

  resources: {}

  nodeSelector: {}
  affinity: {}
  tolerations: []

  securityContext: {}

  labels: {}
  podLabels: {}

  annotations: {}
  podAnnotations: {}

  extraEnv: []
  extraVolumeMounts: []
  extraVolumes: []

################################################################################
web:
  enabled: true

  image:
    repository: guacamole/guacamole
    tag: 1.5.3
    pullPolicy: IfNotPresent
    pullSecret: ""
    uid: 1001
    gid: 0

  port: 8080

  replicas: 1

  resources: {}

  nodeSelector: {}
  affinity: {}
  tolerations: []

  securityContext: {}

  labels: {}
  podLabels: {}

  annotations: {}
  podAnnotations: {}

  extraEnv: []
  extraVolumeMounts: []
  extraVolumes: []

################################################################################
ingress:
  # Only enabled when web.enable is also true
  enabled: false

  host:
  path:

  ingressClassName:

  tls:
    enabled: false
    secretName:

################################################################################
database:
  enabled: true

  image: ghcr.io/cloudnative-pg/postgresql:16.1

  database: guacdb
  owner: guacdb

  secret:
  createSecret:
    create: false
    password: password

  instances: 1

  storage:

  # TODO currently does not set the port on the client, just here for other places to read from
  port: 5432
