{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "guacamole.fullname" . }}-web

  labels:
    app: {{ include "guacamole.labels.app" . }}
    component: web
    chart: {{ include "guacamole.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

spec:
  selector:
    app: {{ include "guacamole.labels.app" . }}
    component: web
    release: {{ .Release.Name }}

  ports:
  - name: web
    port: {{ .Values.web.port }}
    protocol: TCP
{{- end }}